name       : libu2f-server
version    : 1.1.0
release    : 3
source     :
    - https://developers.yubico.com/libu2f-server/Releases/libu2f-server-1.1.0.tar.xz : 8dcd3caeacebef6e36a42462039fd035e45fa85653dcb2013f45e15aad49a277
license    : BSD-2-Clause
component  : security.library
summary    : Yubico Universal 2nd Factor (U2F) Server C Library
description: |
    This is a C library that implements the server-side of the U2F protocol. More precisely, it provides an API for generating the JSON blobs required by U2F devices to perform the U2F Registration and U2F Authentication operations, and functionality for verifying the cryptographic operations. For the host side see libu2f-host.
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(libssl)
    - pkgconfig(check)
    - gengetopt
    - help2man
setup      : |
    %configure --disable-static --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
