name       : libu2f-server
version    : 1.1.0
release    : 5
source     :
    - https://github.com/Yubico/libu2f-server/archive/libu2f-server-1.1.0.tar.gz : 6551109e692c9c4fea61e99f1cd8377e8e54e3033e421cc191da6d673311c860
license    : BSD-2-Clause
component  : security.library
summary    : Yubico Universal 2nd Factor (U2F) Server C Library
description: |
    This is a C library that implements the server-side of the U2F protocol. More precisely, it provides an API for generating the JSON blobs required by U2F devices to perform the U2F Registration and U2F Authentication operations, and functionality for verifying the cryptographic operations. For the host side see libu2f-host.
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(check)
    - gengetopt
    - help2man
setup      : |
    %reconfigure --disable-static --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
