name       : libu2f-server
version    : 1.0.1
release    : 1
source     :
    - https://developers.yubico.com/libu2f-server/Releases/libu2f-server-1.0.1.tar.xz : a618f59051209d6d70c24cf42d64c9b67bd7dd5946b6dbd2c649181d7e8f1f6e
license    : BSD-2-Clause
component  : security.library
summary    : Yubico Universal 2nd Factor (U2F) Server C Library
description: |
    This is a C library that implements the server-side of the U2F protocol. More precisely, it provides an API for generating the JSON blobs required by U2F devices to perform the U2F Registration and U2F Authentication operations, and functionality for verifying the cryptographic operations. For the host side see libu2f-host.
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(libssl)
    - pkgconfig(check)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
